#!/bin/bash
TEST_DIR=tests/

run:
	@clear
	@poetry run python main.py

vision:
	@poetry run python BlocVision/vision.py

robot:
	@poetry run python BlocRobot/

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'


clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage
	rm -f database.db

clean-logs: ## Clean logs
	rm -rf logs/**

clean-env: ## Clean poetry local files
	rm -rf .cache
	rm -rf .venv

format: ## Run pre-commit hooks
	@poetry run black BlocVision
	@poetry run isort --profile black BlocVision
	@poetry run black BlocRobot
	@poetry run isort --profile black BlocRobot
##@poetry run pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	@poetry run pytest -k "not slow"  \
	$(TEST_DIR) --cov=$(PACKAGE_DIR) --cov-report html:./htmlcov \
	--cov-fail-under 90
	@poetry run coverage-badge -fo $(PATH_COV_BADGE)

test-full: ## Run all tests
	@poetry run pytest  \
	$(TEST_DIR) --cov=$(PACKAGE_DIR) --cov-report html:./htmlcov \


check_types:
	@poetry run mypy -p $$(echo $(PACKAGE_DIR) | sed 's/^\///;s/\// /g')
	@poetry run mypy -p $$(echo $(TEST_DIR) | sed 's/^\///;s/\// /g')
